horse_game/horse_game/urls.py
from django.conf import settings
from django.conf.urls import url, include
from django.conf.urls.static import static
from django.contrib import admin
from rest_framework import routers
from accounts.views import (login_view, register_view, logout_view)
from horses.views import HorseList
from horses.api.views import HorseViewSet

router = routers.DefaultRouter()
router.register(r'horses', HorseViewSet)

urlpatterns = [
    
    url(r'^admin/', admin.site.urls),
    url(r'^register/', register_view, name='register'),
    url(r'^login/', login_view, name='login'),
    url(r'^logout/', logout_view, name='logout'),
    url(r'^$', HorseList.as_view()),
    url(r'^horses/', include("horses.urls", namespace='horses')),
    #url(r'^api/auth/token/', obtain_jwt_token),
    url(r'^api/users/', include("accounts.api.urls", namespace='users-api')),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

horse_game/horses/urls.py
from django.conf.urls import url
from django.contrib import admin

from .views import (
	HorseList,
	HorseCreate,
	HorseDetail,
	horse_update,
	horse_delete,
	)

urlpatterns = [
	url(r'^$', HorseList.as_view(), name='list'),
    url(r'^create/$', HorseCreate.as_view(), name='create'),
    url(r'^(?P<pk>[\w-]+)/$', HorseDetail.as_view(), name='detail'),
    url(r'^(?P<pk>[\w-]+)/edit/$', horse_update, name='update'),
    url(r'^(?P<pk>[\w-]+)/delete/$', horse_delete),
    #url(r'^posts/$', "<appname>.views.<function_name>"),
]

horse_game/templates/base.html
{% load staticfiles %}
<!--DOCTYPE html -->
<html>
<head>
<title>{% block head_title %}Horse Game{% endblock head_title %}</title>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">

<link rel='stylesheet' href='https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css' >


<link rel='stylesheet' href='{% static "css/base.css" %}' />
<style>
{% block style %}{% endblock style %}
</style>

{% block head_extra %} {% endblock head_extra %}
</head>
<body>
<div id="fb-root"></div>

{% include "messages_display.html" %}
<div class='container'> 
    <ol class='breadcrumb'>
        <li><a href='{% url "horses:list" %}'>Home</a></li>
        {% block post_detail_link %}
        {% endblock %}

        {% if not request.user.is_authenticated %}
        <li class='pull-right'><a href='{% url "register" %}'>Register</a></li>
        <li class='pull-right'><a href='{% url "login" %}'>Login</a></li>
        {% else %}
        <li class='pull-right'><a href='{% url "logout" %}'>Logout</a></li>
        {% endif %}
    </ol>
{% block content %}{% endblock content %}
</div>



<!-- Latest compiled and minified JavaScript -->
<script   src="http://code.jquery.com/jquery-1.12.2.min.js"   integrity="sha256-lZFHibXzMHo3GGeehn1hudTAP3Sc0uKXBXAzHX1sjtk="   crossorigin="anonymous"></script>


<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>

<script src='https://cdnjs.cloudflare.com/ajax/libs/marked/0.3.5/marked.min.js'></script>


</body>
</html>

horse_game/templates/comment_thread.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}



{% block content %}
{{ object }}



<div class='col-sm-6 col-sm-offset-3'>

        
          <p>{{ comment.content }}</p>
          <footer>via {{ comment.user }} | {{ comment.timestamp|timesince }} ago | {% if comment.children.count > 0 %}{{ comment.children.count }} Comment{% if comment.children.count > 1 %}s{% endif %} {% endif %} {% if request.user == comment.user %}<a href='{{ comment.get_delete_url }}'>Delete</a> {% endif %}</footer>
          <hr/>
          <div>
              {% for child_comment in comment.children %}
                <blockquote>
                <p>{{ child_comment.content }}</p>
                <footer>via {{ child_comment.user }} | {{ child_comment.timestamp|timesince }} ago | {% if request.user == child_comment.user %}<a href='{{ child_comment.get_delete_url }}'>Delete</a>{% endif %}</footer>
                </blockquote>
             {% endfor %}
             {% if request.user.is_authenticated %}
            <form method="POST" action="."> {% csrf_token %}
                {{ form|crispy }}
                <input type='hidden' name='parent_id' value='{{ comment.id }}'>
                <input type='submit' value='Reply' class='btn btn-default'>
            </form>
            {% else %}
            <p>You must login to comment </p>
            {% endif %}
        </div>

    

        <hr/>
</div>


{% endblock content %}

horse_game/templates/confirm_delete.html
{% extends "base.html" %}
{% load urlify %}
{% load crispy_forms_tags %}


{% block head_title %}
{{ instance.title }} | {{ block.super }}
{% endblock head_title %}



{% block content %}

<div class='col-sm-6 col-sm-offset-3'>
  <h1>Confirm Delete</h1>
        
      
            <form method="POST" action="."> {% csrf_token %}
                <p>A re you sure you want to delete: "{{ object.content }}"?</p>
              
                <input type='submit' value='Confirm' class='btn btn-warning'>
                <a href='{{ object.get_absolute_url }}' class='btn btn-default'>Cancel</a>
            </form>
        </div>

    

        <hr/>
</div>


{% endblock content %}

horse_game/templates/form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_title %}
{{ title }} | {{ block.super }}
{% endblock head_title %}

{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>{{ title }}</h1>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>
{% csrf_token %}
{% crispy form %}
</form>
</div>
{% endblock content %}

horse_game/templates/horse_detail.html
{% extends "base.html" %}

{% block head_title %}
{{ horse.name }} | {{ block.super }}
{% endblock head_title %}


 {% block post_detail_link %}
  <li><a href='{{ horse.get_absolute_url }}'>{{ horse.name }}</a></li>
  {% endblock %}

{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>{{ horse.name }} {% if user.is_staff %}<small class="text-muted"><a href="{{ horse.get_admin_url }}">Edit</a></small>{% endif %}</h1>
<p>{{ horse.age }} year old {{ horse.color }} {{ horse.breed }} {{ horse.gender }}, standing {{ horse.height }}hh</p>
<p>Owned by {{ horse.owner }}</p>
</div>
<div class="row">
<div class="col-sm-6">
	<h3>Stats</h3>
{% for stat in horse.visible_stats %}
	<div class="row">
		<div class="col-sm-2">{{ stat.stat }}</div>
		<div class="col-sm-3">
			<div class="progress">
				<div class="progress-bar" role="progressbar" style="width: {{ stat.value|floatformat:"0" }}%" aria-valuenow="{{ stat.value|floatformat:"0" }}" aria-valuemin="0" aria-valuemax="100"></div> 
			</div>  
		</div>
		<div class="col-sm-1">{{ stat.value|floatformat:"0" }}</div>
	</div>
{% endfor %}
</div>
</div>
<div class="row">
<div class="col-sm-6">
	<h3>Genetics</h3>
{% for gene in horse.genotype.all %}
	<div class="row">
		<div class="col-sm-4">{{ gene.gene }}</div>
		<div class="col-sm-2">{{ gene.show_genotype_str }}</div>
	</div>
{% endfor %}
</div>
</div>
{% endblock content %}

horse_game/templates/horse_list.html
{% extends "base.html" %}
{% block content %}


<div class='col-sm-6 col-sm-offset-3'>
    <h1>{{ title }}</h1>
<form method='GET' action='' class='row'>
        <div class='col-sm-6'>
            <div class='input-group'>
                <input class='form-control' type='text' name='q' placeholder='Search posts' value='{{ request.GET.q }}'/>
                <span class='input-group-btn'>
                    <!-- <input class='btn btn-default' type='submit' value='Search' /> -->
                    <button class='btn btn-default' type='submit'>Search <i class="fa fa-search"></i></button>
                </span>
            </div>
        </div>
</form>
{% if not horse_list %}
	<h2>There are no horses to see. <a href="{{ horse.show_create_url }}">Create One?</a></h2>
{% endif %}

{% for horse in horse_list %}
<div class="row">
  <div class="col-sm-12">
	  <h2><a href="{{ horse.get_absolute_url }}">{{ horse.name }}</a></h2>
	  <p>{{ horse.age }} year old {{ horse.color }} {{ horse.breed }}</p>
	  <p>Owned by: {{ horse.owner }}</p>
    </div>
<hr/>
</div>
{% endfor %}


{% if is_paginated %}
  <ul class="pagination">
    {% if page_obj.has_previous %}
      <li><a href="?page={{ page_obj.previous_page_number }}">&laquo;</a></li>
    {% else %}
      <li class="disabled"><span>&laquo;</span></li>
    {% endif %}
    {% for i in paginator.page_range %}
      {% if page_obj.number == i %}
        <li class="active"><span>{{ i }} <span class="sr-only">(current)</span></span></li>
      {% else %}
        <li><a href="?page={{ i }}">{{ i }}</a></li>
      {% endif %}
    {% endfor %}
    {% if page_obj.has_next %}
      <li><a href="?page={{ page_obj.next_page_number }}">&raquo;</a></li>
    {% else %}
      <li class="disabled"><span>&raquo;</span></li>
    {% endif %}
  </ul>
{% endif %}





</div>

{% endblock content %}

horse_game/templates/messages_display.html
 {% if messages %}
    <div class='messages'>

    <ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{% if "html_safe" in message.tags %}{{ message|safe }}{% else %}{{ message }}{% endif %}</li>
    {% endfor %}
    </ul>

    </div>
{% endif %}

horse_game/templates/post_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block head_extra %} 
{{ form.media }}

{% endblock head_extra %}



{% block content %}
<div class='col-sm-6'>
<h1>Preview</h1>
<hr/>
<div class='content-preview'>
    <h3 id='preview-title'></h3>
    <p id='preview-content'></p>
</div>
</div>
<div class='col-sm-6'>
<h1>Form</h1>
<hr/>

<form method='POST' action='' enctype='multipart/form-data'>{% csrf_token %}
{{ form|crispy }}
<input type='submit' class='btn btn-default' value='Create Post' />
</form>
</div>
{% endblock content %}

horse_game/templates/user_detail.html
{% extends "base.html" %}

{% block head_title %}
{{ user.username }} | {{ block.super }}
{% endblock head_title %}


 {% block post_detail_link %}
  <li><a href='{{ user.get_absolute_url }}'>{{ user.title }}</a></li>
  {% endblock %}

{% block content %}
<div class='col-sm-6 col-sm-offset-3'>
<h1>{{ user.username }}</h1>
{% endblock content %}